//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Roboasset
{
    [Serializable]
    public class CollisionPointMsg : Message
    {
        public const string k_RosMessageName = "roboasset_msgs/CollisionPoint";
        public override string RosMessageName => k_RosMessageName;

        //  Message to control the robot in a virtual environment
        //  the robot whill the use the information to simulate real
        //  collision between the robot and the virtual environment
        //  Whether or not virtual object tracked to the robot's
        //  end effector is in collision with the virtual environment
        public bool is_collision;
        //  The point closest to the robot's end effector that is
        //  in the surface of the virtual object
        public Geometry.PointMsg collision_point;

        public CollisionPointMsg()
        {
            this.is_collision = false;
            this.collision_point = new Geometry.PointMsg();
        }

        public CollisionPointMsg(bool is_collision, Geometry.PointMsg collision_point)
        {
            this.is_collision = is_collision;
            this.collision_point = collision_point;
        }

        public static CollisionPointMsg Deserialize(MessageDeserializer deserializer) => new CollisionPointMsg(deserializer);

        private CollisionPointMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.is_collision);
            this.collision_point = Geometry.PointMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.is_collision);
            serializer.Write(this.collision_point);
        }

        public override string ToString()
        {
            return "CollisionPointMsg: " +
            "\nis_collision: " + is_collision.ToString() +
            "\ncollision_point: " + collision_point.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
