//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Roboasset
{
    [Serializable]
    public class PoseDetectionMsg : Message
    {
        public const string k_RosMessageName = "roboasset_msgs/PoseDetection";
        public override string RosMessageName => k_RosMessageName;

        //  ROS2 Message for the media pipe pose detection node
        //  contains the 3d position of each detected body landmark
        //  in the camera frame
        public Std.HeaderMsg header;
        public Geometry.PointMsg nose;
        public Geometry.PointMsg left_eye_inner;
        public Geometry.PointMsg left_eye;
        public Geometry.PointMsg left_eye_outer;
        public Geometry.PointMsg right_eye_inner;
        public Geometry.PointMsg right_eye;
        public Geometry.PointMsg right_eye_outer;
        public Geometry.PointMsg left_ear;
        public Geometry.PointMsg right_ear;
        public Geometry.PointMsg mouth_left;
        public Geometry.PointMsg mouth_right;
        public Geometry.PointMsg left_shoulder;
        public Geometry.PointMsg right_shoulder;
        public Geometry.PointMsg left_elbow;
        public Geometry.PointMsg right_elbow;
        public Geometry.PointMsg left_wrist;
        public Geometry.PointMsg right_wrist;
        public Geometry.PointMsg left_pinky;
        public Geometry.PointMsg right_pinky;
        public Geometry.PointMsg left_index;
        public Geometry.PointMsg right_index;
        public Geometry.PointMsg left_thumb;
        public Geometry.PointMsg right_thumb;
        public Geometry.PointMsg left_hip;
        public Geometry.PointMsg right_hip;
        public Geometry.PointMsg left_knee;
        public Geometry.PointMsg right_knee;
        public Geometry.PointMsg left_ankle;
        public Geometry.PointMsg right_ankle;
        public Geometry.PointMsg left_heel;
        public Geometry.PointMsg right_heel;
        public Geometry.PointMsg left_foot_index;
        public Geometry.PointMsg right_foot_index;

        public PoseDetectionMsg()
        {
            this.header = new Std.HeaderMsg();
            this.nose = new Geometry.PointMsg();
            this.left_eye_inner = new Geometry.PointMsg();
            this.left_eye = new Geometry.PointMsg();
            this.left_eye_outer = new Geometry.PointMsg();
            this.right_eye_inner = new Geometry.PointMsg();
            this.right_eye = new Geometry.PointMsg();
            this.right_eye_outer = new Geometry.PointMsg();
            this.left_ear = new Geometry.PointMsg();
            this.right_ear = new Geometry.PointMsg();
            this.mouth_left = new Geometry.PointMsg();
            this.mouth_right = new Geometry.PointMsg();
            this.left_shoulder = new Geometry.PointMsg();
            this.right_shoulder = new Geometry.PointMsg();
            this.left_elbow = new Geometry.PointMsg();
            this.right_elbow = new Geometry.PointMsg();
            this.left_wrist = new Geometry.PointMsg();
            this.right_wrist = new Geometry.PointMsg();
            this.left_pinky = new Geometry.PointMsg();
            this.right_pinky = new Geometry.PointMsg();
            this.left_index = new Geometry.PointMsg();
            this.right_index = new Geometry.PointMsg();
            this.left_thumb = new Geometry.PointMsg();
            this.right_thumb = new Geometry.PointMsg();
            this.left_hip = new Geometry.PointMsg();
            this.right_hip = new Geometry.PointMsg();
            this.left_knee = new Geometry.PointMsg();
            this.right_knee = new Geometry.PointMsg();
            this.left_ankle = new Geometry.PointMsg();
            this.right_ankle = new Geometry.PointMsg();
            this.left_heel = new Geometry.PointMsg();
            this.right_heel = new Geometry.PointMsg();
            this.left_foot_index = new Geometry.PointMsg();
            this.right_foot_index = new Geometry.PointMsg();
        }

        public PoseDetectionMsg(Std.HeaderMsg header, Geometry.PointMsg nose, Geometry.PointMsg left_eye_inner, Geometry.PointMsg left_eye, Geometry.PointMsg left_eye_outer, Geometry.PointMsg right_eye_inner, Geometry.PointMsg right_eye, Geometry.PointMsg right_eye_outer, Geometry.PointMsg left_ear, Geometry.PointMsg right_ear, Geometry.PointMsg mouth_left, Geometry.PointMsg mouth_right, Geometry.PointMsg left_shoulder, Geometry.PointMsg right_shoulder, Geometry.PointMsg left_elbow, Geometry.PointMsg right_elbow, Geometry.PointMsg left_wrist, Geometry.PointMsg right_wrist, Geometry.PointMsg left_pinky, Geometry.PointMsg right_pinky, Geometry.PointMsg left_index, Geometry.PointMsg right_index, Geometry.PointMsg left_thumb, Geometry.PointMsg right_thumb, Geometry.PointMsg left_hip, Geometry.PointMsg right_hip, Geometry.PointMsg left_knee, Geometry.PointMsg right_knee, Geometry.PointMsg left_ankle, Geometry.PointMsg right_ankle, Geometry.PointMsg left_heel, Geometry.PointMsg right_heel, Geometry.PointMsg left_foot_index, Geometry.PointMsg right_foot_index)
        {
            this.header = header;
            this.nose = nose;
            this.left_eye_inner = left_eye_inner;
            this.left_eye = left_eye;
            this.left_eye_outer = left_eye_outer;
            this.right_eye_inner = right_eye_inner;
            this.right_eye = right_eye;
            this.right_eye_outer = right_eye_outer;
            this.left_ear = left_ear;
            this.right_ear = right_ear;
            this.mouth_left = mouth_left;
            this.mouth_right = mouth_right;
            this.left_shoulder = left_shoulder;
            this.right_shoulder = right_shoulder;
            this.left_elbow = left_elbow;
            this.right_elbow = right_elbow;
            this.left_wrist = left_wrist;
            this.right_wrist = right_wrist;
            this.left_pinky = left_pinky;
            this.right_pinky = right_pinky;
            this.left_index = left_index;
            this.right_index = right_index;
            this.left_thumb = left_thumb;
            this.right_thumb = right_thumb;
            this.left_hip = left_hip;
            this.right_hip = right_hip;
            this.left_knee = left_knee;
            this.right_knee = right_knee;
            this.left_ankle = left_ankle;
            this.right_ankle = right_ankle;
            this.left_heel = left_heel;
            this.right_heel = right_heel;
            this.left_foot_index = left_foot_index;
            this.right_foot_index = right_foot_index;
        }

        public static PoseDetectionMsg Deserialize(MessageDeserializer deserializer) => new PoseDetectionMsg(deserializer);

        private PoseDetectionMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.nose = Geometry.PointMsg.Deserialize(deserializer);
            this.left_eye_inner = Geometry.PointMsg.Deserialize(deserializer);
            this.left_eye = Geometry.PointMsg.Deserialize(deserializer);
            this.left_eye_outer = Geometry.PointMsg.Deserialize(deserializer);
            this.right_eye_inner = Geometry.PointMsg.Deserialize(deserializer);
            this.right_eye = Geometry.PointMsg.Deserialize(deserializer);
            this.right_eye_outer = Geometry.PointMsg.Deserialize(deserializer);
            this.left_ear = Geometry.PointMsg.Deserialize(deserializer);
            this.right_ear = Geometry.PointMsg.Deserialize(deserializer);
            this.mouth_left = Geometry.PointMsg.Deserialize(deserializer);
            this.mouth_right = Geometry.PointMsg.Deserialize(deserializer);
            this.left_shoulder = Geometry.PointMsg.Deserialize(deserializer);
            this.right_shoulder = Geometry.PointMsg.Deserialize(deserializer);
            this.left_elbow = Geometry.PointMsg.Deserialize(deserializer);
            this.right_elbow = Geometry.PointMsg.Deserialize(deserializer);
            this.left_wrist = Geometry.PointMsg.Deserialize(deserializer);
            this.right_wrist = Geometry.PointMsg.Deserialize(deserializer);
            this.left_pinky = Geometry.PointMsg.Deserialize(deserializer);
            this.right_pinky = Geometry.PointMsg.Deserialize(deserializer);
            this.left_index = Geometry.PointMsg.Deserialize(deserializer);
            this.right_index = Geometry.PointMsg.Deserialize(deserializer);
            this.left_thumb = Geometry.PointMsg.Deserialize(deserializer);
            this.right_thumb = Geometry.PointMsg.Deserialize(deserializer);
            this.left_hip = Geometry.PointMsg.Deserialize(deserializer);
            this.right_hip = Geometry.PointMsg.Deserialize(deserializer);
            this.left_knee = Geometry.PointMsg.Deserialize(deserializer);
            this.right_knee = Geometry.PointMsg.Deserialize(deserializer);
            this.left_ankle = Geometry.PointMsg.Deserialize(deserializer);
            this.right_ankle = Geometry.PointMsg.Deserialize(deserializer);
            this.left_heel = Geometry.PointMsg.Deserialize(deserializer);
            this.right_heel = Geometry.PointMsg.Deserialize(deserializer);
            this.left_foot_index = Geometry.PointMsg.Deserialize(deserializer);
            this.right_foot_index = Geometry.PointMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.nose);
            serializer.Write(this.left_eye_inner);
            serializer.Write(this.left_eye);
            serializer.Write(this.left_eye_outer);
            serializer.Write(this.right_eye_inner);
            serializer.Write(this.right_eye);
            serializer.Write(this.right_eye_outer);
            serializer.Write(this.left_ear);
            serializer.Write(this.right_ear);
            serializer.Write(this.mouth_left);
            serializer.Write(this.mouth_right);
            serializer.Write(this.left_shoulder);
            serializer.Write(this.right_shoulder);
            serializer.Write(this.left_elbow);
            serializer.Write(this.right_elbow);
            serializer.Write(this.left_wrist);
            serializer.Write(this.right_wrist);
            serializer.Write(this.left_pinky);
            serializer.Write(this.right_pinky);
            serializer.Write(this.left_index);
            serializer.Write(this.right_index);
            serializer.Write(this.left_thumb);
            serializer.Write(this.right_thumb);
            serializer.Write(this.left_hip);
            serializer.Write(this.right_hip);
            serializer.Write(this.left_knee);
            serializer.Write(this.right_knee);
            serializer.Write(this.left_ankle);
            serializer.Write(this.right_ankle);
            serializer.Write(this.left_heel);
            serializer.Write(this.right_heel);
            serializer.Write(this.left_foot_index);
            serializer.Write(this.right_foot_index);
        }

        public override string ToString()
        {
            return "PoseDetectionMsg: " +
            "\nheader: " + header.ToString() +
            "\nnose: " + nose.ToString() +
            "\nleft_eye_inner: " + left_eye_inner.ToString() +
            "\nleft_eye: " + left_eye.ToString() +
            "\nleft_eye_outer: " + left_eye_outer.ToString() +
            "\nright_eye_inner: " + right_eye_inner.ToString() +
            "\nright_eye: " + right_eye.ToString() +
            "\nright_eye_outer: " + right_eye_outer.ToString() +
            "\nleft_ear: " + left_ear.ToString() +
            "\nright_ear: " + right_ear.ToString() +
            "\nmouth_left: " + mouth_left.ToString() +
            "\nmouth_right: " + mouth_right.ToString() +
            "\nleft_shoulder: " + left_shoulder.ToString() +
            "\nright_shoulder: " + right_shoulder.ToString() +
            "\nleft_elbow: " + left_elbow.ToString() +
            "\nright_elbow: " + right_elbow.ToString() +
            "\nleft_wrist: " + left_wrist.ToString() +
            "\nright_wrist: " + right_wrist.ToString() +
            "\nleft_pinky: " + left_pinky.ToString() +
            "\nright_pinky: " + right_pinky.ToString() +
            "\nleft_index: " + left_index.ToString() +
            "\nright_index: " + right_index.ToString() +
            "\nleft_thumb: " + left_thumb.ToString() +
            "\nright_thumb: " + right_thumb.ToString() +
            "\nleft_hip: " + left_hip.ToString() +
            "\nright_hip: " + right_hip.ToString() +
            "\nleft_knee: " + left_knee.ToString() +
            "\nright_knee: " + right_knee.ToString() +
            "\nleft_ankle: " + left_ankle.ToString() +
            "\nright_ankle: " + right_ankle.ToString() +
            "\nleft_heel: " + left_heel.ToString() +
            "\nright_heel: " + right_heel.ToString() +
            "\nleft_foot_index: " + left_foot_index.ToString() +
            "\nright_foot_index: " + right_foot_index.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
