//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Roboasset
{
    [Serializable]
    public class ControlModeServiceResponse : Message
    {
        public const string k_RosMessageName = "roboasset_msgs/ControlModeService";
        public override string RosMessageName => k_RosMessageName;

        //  If not '', contains the error message
        public string ret_value;

        public ControlModeServiceResponse()
        {
            this.ret_value = "";
        }

        public ControlModeServiceResponse(string ret_value)
        {
            this.ret_value = ret_value;
        }

        public static ControlModeServiceResponse Deserialize(MessageDeserializer deserializer) => new ControlModeServiceResponse(deserializer);

        private ControlModeServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ret_value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ret_value);
        }

        public override string ToString()
        {
            return "ControlModeServiceResponse: " +
            "\nret_value: " + ret_value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
